// UI Data Part 4 (Entries 900 - 1200)
module.exports = {
  "Town Hall": "町役場",
  "Mule": "荷ロバ",
  "Mules": "荷ロバ",
  "Tree trunk": "木の幹",
  "Teuton Tent": "テウトンの天幕",
  "Unit": "ユニット",
  "Wall": "防壁",
  "Warehouse": "倉庫",
  "Small well": "小さな井戸",
  "Large well": "大きな井戸",
  "Witch hut": "魔女の小屋",
  "Wolf": "オオカミ",
  "Wolves": "オオカミ（群れ）",
  "Wolf (aggressive)": "オオカミ（凶暴）",
  "Unit under attack": "部隊が攻撃を受けています",
  "Building under attack": "建物が攻撃を受けています",
  "Settlement captured": "拠点が占領されました",
  "Notes changed": "任務記録が更新されました",
  "Diplomacy relations changed": "外交関係が変更されました",
  "Not enough gold": "ゴールドが不足しています",
  "Not enough food": "食料が不足しています",
  "Not enough population": "人口が不足しています",
  "Can target friendly units only": "味方ユニットのみ対象にできます",
  "Can target units only": "ユニットのみ対象にできます",
  "Can target enemy units only": "敵ユニットのみ対象にできます",
  "Location message": "位置情報メッセージ",
  "Unable to train units - there are enemies around": "周囲に敵がいるため訓練できません",
  "None": "なし",
  "Wealth": "富裕",
  "Riches": "裕福",
  "Fortune": "繁栄",
  "Concentration gem": "集中の宝玉",
  "Fur gloves": "毛皮の手袋",
  "Elimination": "敵全滅",
  "Score Limit": "目標スコア到達",
  "Time limit (military rating)": "制限時間（軍事評価）",
  "Time Limit(military rating)": "制限時間（軍事評価）",
  "Time limit (score)": "制限時間（総スコア）",
  "Time Limit(score)": "制限時間（総スコア）",
  "Coastal": "海岸",
  "Continent": "大陸",
  "Island": "島嶼",
  "Large islands": "大島群",
  "Mediterranean": "地中海",
  "Mountainous": "山岳",
  "Small islands": "小島群",
  "Random": "ランダム",
  "Apprentice": "見習い",
  "Fighter": "闘士",
  "Warrior": "戦士",
  "Veteran": "歴戦の勇士",
  "Master": "達人",
  "Chieftain": "首長",
  "Lord": "領主",
  "Champion": "覇者",
  "Hero": "英雄",
  "Legend": "伝説の英雄",
  "Deity": "軍神",
  "Cheater": "チーター",
  "Tree 1": "樹木 1",
  "Broad-leaved": "広葉樹",
  "Tree 2": "樹木 2",
  "Tree 3": "樹木 3",
  "Tree 4": "樹木 4",
  "Tree 5": "樹木 5",
  "Tree 6": "樹木 6",
  "Pine tree 1": "松 1",
  "Pine trees": "松の木",
  "Pine tree 2": "松 2",
  "Pine tree 3": "松 3",
  "Pine tree 4": "松 4",
  "Pine tree 5": "松 5",
  "Pine tree 6": "松 6",
  "Pine tree 7": "松 7",
  "Pine tree 8": "松 8",
  "Dead tree 1": "枯れ木 1",
  "Dead trees": "枯れ木",
  "Dead tree 2": "枯れ木 2",
  "Dead tree 3": "枯れ木 3",
  "Dead tree 4": "枯れ木 4",
  "Dead tree 5": "枯れ木 5",
  "Dead tree 6": "枯れ木 6",
  "Dead tree 7": "枯れ木 7",
  "Dead tree 8": "枯れ木 8",
  "Dead tree 9": "枯れ木 9",
  "Stump 1": "切り株 1",
  "Stumps": "切り株",
  "Stump 2": "切り株 2",
  "Bush 1": "低木 1",
  "Bushes": "低木",
  "Green bushes": "緑の低木",
  "Bush 2": "低木 2",
  "Bush 3": "低木 3",
  "Bush 4": "低木 4",
  "Bush 5": "低木 5",
  "Bush 6": "低木 6",
  "Dead bush 1": "枯れ低木 1",
  "Dead bushes": "枯れ低木",
  "Dead bush 2": "枯れ低木 2",
  "Corn (field)": "トウモロコシ畑",
  "Corn (small)": "トウモロコシ（小）",
  "Corn (big)": "トウモロコシ（大）",
  "Rock 1": "岩 1",
  "Rocks": "岩石",
  "Rock 2": "岩 2",
  "Rock 3": "岩 3",
  "Stone 1": "石 1",
  "Stones": "小石",
  "Stone 2": "石 2",
  "Stone 3": "石 3",
  "Stone 4": "石 4",
  "Stone 5": "石 5",
  "Field": "平原",
  "Other": "その他",
  "Cliff with a hole": "洞窟のある崖",
  "Swamp (big)": "大湿地",
  "Swamp 1 (small)": "小湿地 1",
  "Swamp 2 (small)": "小湿地 2",
  "Skeleton 1": "骸骨 1",
  "Skeletons": "骸骨",
  "Skeleton 2": "骸骨 2",
  "Stump 3": "切り株 3",
  "Stump 4": "切り株 4",
  "Stump 5": "切り株 5",
  "Stump 6": "切り株 6",
  "Stumps 1": "切り株群 1",
  "Stumps 2": "切り株群 2",
  "Stumps 3": "切り株群 3",
  "Bush 7": "低木 7",
  "Bush 8": "低木 8",
  "Bush 9": "低木 9",
  "Bush 10": "低木 10",
  "Chopped trees 1": "伐採木 1",
  "Chopped trees": "伐採木",
  "Chopped trees 2": "伐採木 2",
  "Chopped trees 3": "伐採木 3",
  "Chopped trees 4": "伐採木 4",
  "Chopped trees 5": "伐採木 5",
  "Chopped trees 6": "伐採木 6",
  "Trunk heap 1": "丸太の山 1",
  "Trunk heaps": "丸太の山",
  "Trunk heap 2": "丸太の山 2",
  "Trunk heap 3": "丸太の山 3",
  "Broken cart 1": "壊れた荷車 1",
  "Broken cart": "壊れた荷車",
  "Broken cart 2": "壊れた荷車 2",
  "Broken cart 3": "壊れた荷車 3",
  "Broken cart 4": "壊れた荷車 4",
  "Skeleton 3": "骸骨 3",
  "Skeleton 4": "骸骨 4",
  "Skeleton 5": "骸骨 5",
  "Skeleton 6": "骸骨 6",
  "Skeleton 7": "骸骨 7",
  "Skeleton 8": "骸骨 8",
  "Skeleton 9": "骸骨 9",
  "Skeleton 10": "骸骨 10",
  "Skeleton 11": "骸骨 11",
  "Skeleton 12": "骸骨 12",
  "Skull": "頭蓋骨",
  "Rock 4": "岩 4",
  "Rock 5": "岩 5",
  "Rock 6": "岩 6",
  "Rock 7": "岩 7",
  "Rock 8": "岩 8",
  "Rock 9": "岩 9",
  "Stone 6": "石 6",
  "Stone 7": "石 7",
  "Stone 8": "石 8",
  "Crops 3": "作物 3",
  "Crops 4": "作物 4",
  "Ground 1": "地面 1",
  "Ground 2": "地面 2",
  "Ground 3": "地面 3",
  "Grass 1": "草地 1",
  "Grass 2": "草地 2",
  "Grass 3": "草地 3",
  "Mountain rocks": "山岳岩",
  "Roads": "道路",
  "Sand": "砂地",
  "Shore rocks": "海岸岩",
  "Shallow water": "浅瀬",
  "Roman roads": "ローマ街道",
  "Invalid": "無効",
  "You were eliminated.": "あなたの勢力は全滅しました。",
  "You lose after %s1:0%s2 minutes": "%s1:0%s2 分経過後に敗北しました",
  "You lose after %s1:%s2 minutes": "%s1:%s2 分経過後に敗北しました",
  "Score limit (%s1).": "スコア上限到達（%s1）。",
  "You lost.": "あなたの敗北です。",
  "Sudden death": "サドンデス",
  "Your team is near the score limit (%s1/%s2).": "自チームが目標スコアに近づいています（%s1/%s2）。",
  "Another team is near the score limit (%s1/%s2).": "他チームが目標スコアに近づいています（%s1/%s2）。",
  "You won!": "あなたの勝利です！",
  "Sudden death (%s1:0%s2)": "サドンデス（%s1:0%s2）",
  "Sudden death (%s1:%s2)": "サドンデス（%s1:%s2）",
  "Time limit (%s1:0%s2 minutes left)": "制限時間（残り %s1:0%s2 分）",
  "Time limit (%s1:%s2 minutes left)": "制限時間（残り %s1:%s2 分）",
  "You win.": "あなたの勝利です。",
  "You lose.": "あなたの敗北です。",
  "You win after %s1:0%s2 minutes": "%s1:0%s2 分経過後に勝利しました",
  "You win after %s1:%s2 minutes": "%s1:%s2 分経過後に勝利しました",
  "%s1 (Requires equipment from blacksmith)": "%s1（要・鍛冶屋での装備研究）",
  "You need to select more units to build catapult": "カタパルトを建造するにはさらに多くのユニットを選択してください",
  "%s1 (requires %s2 food)": "%s1（要・食料 %s2）",
  "%s1 (requires %s2 gold)": "%s1（要・ゴールド %s2）",
  "Heal not availabale": "治療を実行できません",
  "Inn found: %s1, %s2.": "宿屋を発見：%s1、%s2。",
  "This inn is closed.": "この宿屋は閉鎖されています。",
  "Gather your party before travelling.": "移動する前にパーティー全員を集合させてください。",
  "You must wait for the current ritual to be completed": "現在進行中の儀式が完了するまでお待ちください",
  "%s1 (%s2 druids or priests required)": "%s1（ドルイドまたは神官が %s2 名必要）",
  "There are no Teuton tents on the map": "マップ上にテウトンの天幕が存在しません",
  "%s1 (At least one druid or priest required)": "%s1（ドルイドまたは神官が最低1名必要）",
  "Cannot train units": "ユニットを訓練できません",
  "%s1 is researching": "%s1 を研究中",
  "%s1 available": "%s1 が利用可能になりました",
  "%s1 (requires %s2)": "%s1（要・%s2）",
  "No more available": "これ以上利用可能なものはありません",
  "Chaotic": "乱戦",
  "Defensive": "防衛重視",
  "Random map": "ランダムマップ",
  "Default": "デフォルト",
  "Low": "低",
  "Normal": "普通",
  "High": "高",
  "Spring": "春",
  "Autumn": "秋",
  "Winter": "冬",
  "Slow": "低速",
  "Fast": "高速",
  "Fastest": "超高速",
  "Variable": "可変",
  "Small": "小",
  "Huge": "巨大",
  "unknown": "不明",
  "random": "ランダム",
  "Team 1": "チーム 1",
  "Team 2": "チーム 2",
  "Team 3": "チーム 3",
  "Team 4": "チーム 4",
  "Rank": "階級",
  "Single player games": "シングルプレイ対戦数",
  "Multiplayer games": "マルチプレイ対戦数",
  "Game time": "総プレイ時間",
  "Favorite nation": "お気に入りの勢力",
  "Favorite unit": "お気に入りのユニット",
  "Resources spent": "総消費資源",
  "Units eliminated": "撃破ユニット数",
  "Units lost": "喪失ユニット数",
  "Health spent for rituals": "儀式で消費した生命力",
  "Most experienced unit": "最高経験値ユニット",
  "Maximum number of units": "最大ユニット数",
  "Unknown": "不明",
  "Hours": "時間",
  "military rating": "軍事評価",
  "food": "食料",
  "gold": "ゴールド",
  "won": "勝",
  "The game instances have become inconsistent.": "ゲームインスタンス間で非同期が発生しました。",
  "Do you realy want to delete both sides of this cave?": "本当にこの洞窟の両端を削除しますか？",
  "Do you realy want to delete this townhall and the whole settlement?": "本当にこの町役場と拠点全体を削除しますか？",
  "(New group)": "（新規グループ）",
  "(Unnamed)": "（名称未設定）",
  "New note": "新規ノート",
  "New sequence": "新規シーケンス",
  "New item type": "新規アイテムタイプ",
  "Named units": "固有名称ユニット",
  "Items": "アイテム一覧",
  "Scenario": "シナリオ",
  "Players diplomacy": "プレイヤー外交",
  "Area properties": "エリアプロパティ",
  "Settlements": "拠点一覧",
  "Item types": "アイテムタイプ一覧",
  "Custom": "カスタム",
  "Customized": "カスタマイズ済",
  "Standard": "標準",
  "%s1 (Hotkey : %s2)": "%s1（ショートカット：%s2）",
  "Bad conversation startup string": "不正な会話開始文字列です",
  "Select a location to use the item on": "アイテムを使用する場所を選択",
  "Select an object to use the item with": "アイテムを使用する対象オブジェクトを選択",
  "Replay": "リプレイ",
  "You win": "勝利",
  "This replay is in invalid format and cannot be loaded. It has probably been saved with a different version of the game!": "このリプレイは無効な形式のため読込できません。別バージョンのゲームで保存された可能性があります！",
  "Do you really want to restart?": "本当に最初からやり直しますか？",
  "Do you really want to surrender?": "本当に降伏しますか？",
  "Do you really want to quit?": "本当に終了しますか？",
  "Give item to this unit": "このユニットにアイテムを渡す",
  "Put item in holder": "アイテムを容器に格納する",
  "Drop item on the ground": "アイテムを地面に捨てる",
  "The game was canceled by the host": "ホストによってゲームがキャンセルされました",
  "You were kicked from the game": "ゲームからキック（追放）されました",
  "Cannot join game - different protocol version": "プロトコルバージョンが異なるためゲームに参加できません",
  "Map Default": "マップデフォルト",
  "Description: %s1": "説明：%s1",
  "Map description: %s1": "マップ説明：%s1",
  "Unnamed": "無名",
  "Players diplomacy/": "プレイヤー外交／",
  "Players/": "プレイヤー／",
  "Delete decorations": "装飾物を削除",
  "Selecting object(s)": "オブジェクトを選択中",
  "Object: [ None ]": "オブジェクト：[ なし ]"
};
