// UI Data Part 2 (Entries 300 - 600)
module.exports = {
  "Click to learn from unit": "クリックして部隊から学習",
  "Right-click to learn from unit": "右クリックして部隊から学習",
  "Click to heal this unit": "クリックしてこのユニットを治療",
  "Right-click to heal this unit": "右クリックしてこのユニットを治療",
  "Click to hide all units around this position": "クリックしてこの位置周辺の全ユニットを隠蔽",
  "Right-click to follow this unit": "右クリックしてこのユニットを追従",
  "Right-click to fire at this position": "右クリックしてこの位置へ射撃",
  "Click on this townhall to start sending resources": "この町役場をクリックして資源輸送を開始",
  "Click on this outpost to start sending resources": "この前哨基地をクリックして資源輸送を開始",
  "Click on this village to start sending resources": "この村をクリックして資源輸送を開始",
  "Right-click on this townhall to start sending resources": "この町役場を右クリックして資源輸送を開始",
  "Right-click on this outpost to start sending resources": "この前哨基地を右クリックして資源輸送を開始",
  "Right-click on this village to start sending resources": "この村を右クリックして資源輸送を開始",
  "Right-click to send all units to this position": "右クリックして全ユニットをこの位置へ派遣",
  "Cancel Command": "コマンドキャンセル",
  "Help (F1)": "ヘルプ (F1)",
  "Diplomacy (F5)": "外交 (F5)",
  "Quick save (F6)": "クイックセーブ (F6)",
  "Select party (F7)": "パーティー選択 (F7)",
  "Notes (F8)": "任務記録 (F8)",
  "Quick load (F9)": "クイックロード (F9)",
  "Main menu (F10)": "メインメニュー (F10)",
  "Chat (Enter)": "チャット (Enter)",
  "Minimap (Space)": "ミニマップ (Space)",
  "Name:": "名前：",
  "Back": "戻る",
  "Save (Crtl+S)": "保存 (Ctrl+S)",
  "Follow link (F2)": "リンク先へ移動 (F2)",
  "Create dialog:": "ダイアログ作成：",
  "Number of tabs:": "タブ数：",
  "Create!": "作成！",
  "Create control:": "コントロール作成：",
  "Relative to:": "相対位置：",
  "Above": "上",
  "Below": "下",
  "Left": "左",
  "Right": "右",
  "Inside": "内部",
  "Padding:": "余白：",
  "Add to tab:": "タブに追加：",
  "Compile": "コンパイル",
  "Save": "保存",
  "Run": "実行",
  "Transportation": "輸送",
  "Rollover text": "ホバーテキスト",
  "General": "全般",
  "Maps": "マップ一覧",
  "Name": "名前",
  "Author": "作者",
  "Description": "説明",
  "Starting map": "開始マップ",
  "Starting player": "開始プレイヤー",
  "Race (interface)": "種族（インターフェース）",
  "Map image": "マップ画像",
  "Set": "設定",
  "New": "新規作成",
  "Import adventure maps": "アドベンチャーマップ読込",
  "Import scenario map": "シナリオマップ読込",
  "Edit": "編集",
  "Delete": "削除",
  "Location": "位置",
  "Shape": "形状",
  "Circular": "円形",
  "Rectangular": "矩形",
  "View Area": "エリア表示",
  "Delete Area": "エリア削除",
  "Transportation area": "輸送エリア",
  "Destination map": "行先マップ",
  "Destination area": "行先エリア",
  "Phrase": "台詞",
  "Phrases": "台詞一覧",
  "Phrase Props": "台詞プロパティ",
  "Properties": "プロパティ",
  "New phrase": "新規台詞",
  "Delete phrase": "台詞削除",
  "Delete conversation": "会話削除",
  "Move phrase up": "台詞を上へ",
  "Move phrase down": "台詞を下へ",
  "Phrase label": "台詞ラベル",
  "Actor": "話者",
  "Choose text": "選択肢テキスト",
  "Phrase text": "台詞本文",
  "Prev phrase": "前の台詞",
  "Next phrase": "次の台詞",
  "Follow up type": "後続タイプ",
  "Follow ups": "後続台詞",
  "Condition script (bool, Unit prev_actor, Unit actor)": "条件スクリプト (bool, Unit prev_actor, Unit actor)",
  "Action script (void, Unit prev_actor, Unit actor)": "アクションスクリプト (void, Unit prev_actor, Unit actor)",
  "Return script (str Out, Unit prev_actor, Unit actor)": "返答スクリプト (str Out, Unit prev_actor, Unit actor)",
  "Comments": "コメント",
  "Conversation name": "会話名",
  "Starting phrase type": "開始台詞タイプ",
  "Starting phrases": "開始台詞",
  "Actors": "登場人物",
  "Restore view when done": "終了時に視点を復帰",
  "Mini map image file": "ミニマップ画像ファイル",
  "No Fog": "霧なし",
  "No Exploration": "未探索なし",
  "Start: 0,0": "開始位置：0,0",
  "Set starting point": "開始位置を設定",
  "Goto starting point": "開始位置へ移動",
  "Delete all": "すべて削除",
  "Player 1": "プレイヤー 1",
  "Player 2": "プレイヤー 2",
  "Player 3": "プレイヤー 3",
  "Player 4": "プレイヤー 4",
  "Player 5": "プレイヤー 5",
  "Player 6": "プレイヤー 6",
  "Player 7": "プレイヤー 7",
  "Player 8": "プレイヤー 8",
  "Player 9": "プレイヤー 9",
  "Player 10": "プレイヤー 10",
  "Player 11": "プレイヤー 11",
  "Player 12": "プレイヤー 12",
  "Player 13": "プレイヤー 13",
  "Player 14": "プレイヤー 14",
  "Player 15": "プレイヤー 15",
  "Player 16": "プレイヤー 16",
  "Cease fire": "停戦",
  "Shared view": "視界共有",
  "Shared support": "補給共有",
  "Shared control": "操作共有",
  "Mutual relations": "相互関係",
  "Allied victory": "同盟勝利",
  "Adventure Palette": "アドベンチャーパレット",
  "Group name": "グループ名",
  "Select": "選択",
  "Select All": "すべて選択",
  "Remove": "除外",
  "Add selection": "選択対象を追加",
  "Select a place for this inn": "この宿屋の設置場所を選択",
  "Class": "クラス",
  "Class comes here": "クラスをここに設定",
  "Contents": "内容物",
  "Slot 2": "スロット 2",
  "Slot 3": "スロット 3",
  "Slot 4": "スロット 4",
  "View item holder": "アイテム容器を表示",
  "Delete item holder": "アイテム容器を削除",
  "Wear bonus": "装備ボーナス",
  "Use script": "使用スクリプト",
  "Type": "タイプ",
  "Image file": "画像ファイル",
  "Browse": "参照",
  "Sound file": "音声ファイル",
  "Important": "重要",
  "Amount": "数量",
  "Reset": "リセット",
  "Max. Attack": "最大攻撃力",
  "Slashing defence": "斬撃防御",
  "Piercing defence": "刺突防御",
  "Level": "レベル",
  "Experience": "経験値",
  "Health": "体力",
  "Healing": "治癒量",
  "Use count": "使用回数",
  "Target:": "対象：",
  "No target": "対象なし",
  "Object": "オブジェクト",
  "Script:": "スクリプト：",
  "Item class": "アイテムクラス",
  "Item holder": "アイテム容器",
  "View": "表示",
  "Map": "マップ",
  "Position": "位置",
  "Icon": "アイコン",
  "Set location": "位置を設定",
  "View location": "位置を表示",
  "Clear location": "位置を消去",
  "Delete note": "ノートを削除",
  "Groups": "グループ一覧",
  "Settlement": "拠点",
  "Stats": "能力値",
  "Visuals": "外観",
  "Inventory": "所持品",
  "Owner player": "所有プレイヤー",
  "Script name": "スクリプト名",
  "View object": "オブジェクトを表示",
  "View objects": "オブジェクト一覧を表示",
  "Display name": "表示名",
  "Set Inn Position": "宿屋の位置を設定",
  "Select all": "すべて選択",
  "Group": "グループ",
  "Member of": "所属グループ",
  "Add": "追加",
  "Settlement name": "拠点名",
  "Gold amount": "ゴールド量",
  "Food amount": "食料量",
  "Efficiency level": "効率レベル",
  "Population": "人口",
  "Max population": "最大人口",
  "Experience level": "経験値レベル",
  "Template unit": "テンプレートユニット",
  "Messenger status": "伝令ステータス",
  "Party": "パーティー",
  "No AI control": "AI制御を無効化",
  "Unit doesn't eat": "食事不要",
  "Gold": "ゴールド",
  "Food": "食料",
  "Queue icon": "キューアイコン",
  "Selection icon": "選択アイコン",
  "Entity": "エンティティ",
  "Slot 1": "スロット 1",
  "Neck": "首",
  "Body": "胴体",
  "Left hand": "左手",
  "Right hand": "右手",
  "Owner": "所有者",
  "View outpost": "前哨基地を表示",
  "Control": "操作",
  "AI": "AI",
  "Starting point": "開始地点",
  "All": "すべて",
  "Strongholds": "要塞一覧",
  "Villages": "村一覧",
  "Outposts": "前哨基地一覧",
  "Pop": "人口",
  "Equalize": "均等化",
  "Efficiency": "効率",
  "Victory condition": "勝利条件",
  "Threshold": "目標値",
  "Single Player Only": "シングルプレイ専用",
  "Source": "ソース",
  "Prerequisite sequences": "前提シーケンス",
  "Delete sequence": "シーケンス削除",
  "Autorun allowed": "自動実行を許可",
  "New Scenario": "新規シナリオ",
  "New Adventure": "新規アドベンチャー",
  "Open Adventure...": "アドベンチャーを開く...",
  "Open Scenario...": "シナリオを開く...",
  "Save this adventure/scenario": "このアドベンチャー/シナリオを保存",
  "Save As...": "名前を付けて保存...",
  "Test this map": "このマップをテスト",
  "Exit": "終了",
  "Brush size:": "ブラシサイズ：",
  "Hint: Right button cycles decors": "ヒント：右クリックで装飾物を切り替え",
  "Density": "密度",
  "Right button sets direction": "右クリックで向きを設定",
  "Shift and right button sets": "Shift + 右クリックで設定",
  "opposite direction": "逆向き",
  "Hint: Right button selects amount": "ヒント：右クリックで数量を選択",
  "Hint: Right button selects level": "ヒント：右クリックでレベルを選択",
  "Cycle seasons": "季節切り替え",
  "Open map wizard": "マップウィザードを開く",
  "Toggle map tools window": "マップツールウィンドウ切替",
  "Toggle mini map": "ミニマップ切替",
  "Open new adventure/scenario editor window": "新規エディタウィンドウを開く",
  "Hide/Show Interface Windows": "インターフェースウィンドウ表示切替",
  "View selection properties": "選択オブジェクトのプロパティ表示",
  "Tools palette": "ツールパレット",
  "Tool options": "ツールオプション",
  "Ok": "OK",
  "Message": "メッセージ",
  "File Name :": "ファイル名：",
  "Open": "開く",
  "Cancel": "キャンセル",
  "Strength": "強度",
  "X Step": "X ステップ",
  "Y Step": "Y ステップ",
  "Player": "プレイヤー",
  "Gates": "城門",
  "Tower To Place": "配置する監視塔",
  "Horizontal distance": "水平距離",
  "Vertical distance": "垂直距離",
  "Players": "プレイヤー数",
  "Restrictions": "制限事項",
  "Generate Random Map": "ランダムマップ生成",
  "Map Type": "マップタイプ",
  "Map Size": "マップサイズ",
  "Season": "季節",
  "Team": "チーム",
  "Generate": "生成",
  "Decorations": "装飾物",
  "ItemHolders": "アイテム容器",
  "Ruins": "遺跡",
  "Shipyards": "造船所",
  "Stonehenge": "ストーンヘンジ",
  "Teleports": "テレポート",
  "TeutonTents": "テウトンの天幕",
  "Trees": "樹木",
  "Wildlife": "野生動物",
  "Scenario Palette": "シナリオパレット",
  "Druid King Editor": "ケルトの王 エディター",
  "Hint: Right button selects terrain or terrain group": "ヒント：右クリックで地形または地形グループを選択",
  "Test results": "テスト結果",
  "Test anyway": "強制テスト実行",
  "Yes": "はい",
  "No": "いいえ",
  "HELP": "ヘルプ",
  "Start": "開始",
  "Adventure Description": "アドベンチャー概要",
  "Adventures": "アドベンチャー一覧",
  "Difficulty:": "難易度：",
  "Credits": "クレジット",
  "Close": "閉じる",
  "Shared vision": "視界共有",
  "Your policy": "自国の態度",
  "Their policy": "相手の態度",
  "Diplomacy": "外交",
  "status": "ステータス"
};
