// UI Data Part 3 (Entries 600 - 900)
module.exports = {
  "Load game": "ゲーム読込",
  "Save replay": "リプレイ保存",
  "Options": "オプション",
  "Restart": "やり直す",
  "Statistics": "統計情報",
  "Quit": "終了",
  "Please wait while other players are aware of your disconnection...": "切断通知を他のプレイヤーに送信中です。お待ちください...",
  "Exit now": "今すぐ退出",
  "Main menu": "メインメニュー",
  "Save game": "ゲーム保存",
  "Surrender": "降伏",
  "Scroll speed": "スクロール速度",
  "Reverse speakers": "左右スピーカー反転",
  "Conversations": "会話音量",
  "Unit speech": "ユニット音声",
  "Nature sounds": "環境音",
  "Sound effects": "効果音",
  "Play music": "音楽再生",
  "Force fewer hero models": "英雄モデルを簡略化",
  "Turn off object animations": "オブジェクトのアニメーションを無効化",
  "Turn off water animation": "水面のアニメーションを無効化",
  "Music and sound": "音楽とサウンド",
  "Graphics": "グラフィック",
  "Resolution": "解像度",
  "(saves processor time)": "（CPU負荷を軽減）",
  "(saves memory)": "（メモリを節約）",
  "Game speed": "ゲーム速度",
  "OK": "OK",
  "Send": "送信",
  "Send location": "位置を送信",
  "Send to all": "全員に送信",
  "Send to allies": "同盟国に送信",
  "Send to player": "プレイヤーに送信",
  "Chat": "チャット",
  "Game type:": "ゲームタイプ：",
  "Load": "読込",
  "Change player": "プレイヤー変更",
  "Tutorial": "チュートリアル",
  "Adventure": "アドベンチャー",
  "Single player": "シングルプレイ",
  "Multiplayer": "マルチプレイ",
  "Editor": "エディター",
  "Player name": "プレイヤー名",
  "Nation": "勢力",
  "Bonus": "ボーナス",
  "I'm ready": "準備完了",
  "Host IP:": "ホストIP：",
  "Game description": "ゲーム概要",
  "Settings": "設定",
  "Join": "参加",
  "Host": "ホスト作成",
  "Game list": "ゲーム一覧",
  "Internet host:": "インターネットホスト：",
  "Refresh": "更新",
  "Notes": "任務記録",
  "No active notes": "進行中の記録はありません",
  "Celtic Kings": "ケルトの王",
  "Paused ...": "一時停止中...",
  "Rename": "名前変更",
  "New player": "新規プレイヤー",
  "Game settings": "ゲーム設定",
  "General settings": "一般設定",
  "Map type:": "マップタイプ：",
  "Season:": "季節：",
  "Limit:": "制限：",
  "World population:": "世界人口：",
  "Starting gold:": "初期ゴールド：",
  "Game speed:": "ゲーム速度：",
  "Disable bonuses": "ボーナス無効",
  "No fog": "霧なし",
  "No exploration": "未探索なし",
  "Random map settings": "ランダムマップ設定",
  "Defaults": "デフォルト",
  "Disable caves": "洞窟無効",
  "Disable Teuton tents": "テウトンの天幕無効",
  "Disable stonehenges": "ストーンヘンジ無効",
  "Disable ruins": "遺跡無効",
  "Disable outposts": "前哨基地無効",
  "Disable villages": "村無効",
  "Disable strongholds": "要塞無効",
  "Disable wildlife": "野生動物無効",
  "Map size:": "マップサイズ：",
  "Random map type:": "ランダムマップ種別：",
  "Maximum players allowed:": "最大参加プレイヤー数：",
  "Players joined:": "参加中プレイヤー：",
  "Save Game Map Settings Panel": "ゲーム設定パネルの保存",
  "Description:": "説明：",
  "Custom map": "カスタムマップ",
  "Maps:": "マップ：",
  "Resources": "資源",
  "Gold production": "ゴールド生産量",
  "Units": "ユニット",
  "Scores": "スコア",
  "Game time here": "経過時間",
  "You lose": "敗北",
  "You Win!": "勝利！",
  "Arena": "闘技場",
  "Structures": "建築物",
  "Stronghold (Gaul)": "要塞（ガリア）",
  "Arena SW": "闘技場（南西）",
  "Arena SE": "闘技場（南東）",
  "Barracks": "兵舎",
  "Shipyard": "造船所",
  "Village Hall": "村役場",
  "Well": "井戸",
  "Gaul Blacksmith": "ガリアの鍛冶屋",
  "Blacksmith": "鍛冶屋",
  "Water": "水域",
  "Boat wreck": "難破船",
  "Item holders": "アイテム容器",
  "Boulder": "巨石",
  "Caesar": "カエサル",
  "Heroes": "英雄",
  "Caesar (Roman)": "カエサル（ローマ）",
  "Catapult": "カタパルト",
  "Chest": "宝箱",
  "Others": "その他",
  "Cliff (dirt)": "崖（土）",
  "Rocks 1": "岩 1",
  "Rocks 2": "岩 2",
  "Rocks 3": "岩 3",
  "Cliff (large) 1": "大崖 1",
  "Cliff (large) 2": "大崖 2",
  "Cliff (large) 3": "大崖 3",
  "Crops 1": "農作物 1",
  "Crops 2": "農作物 2",
  "Crops field": "農地",
  "Crow": "カラス",
  "Crows": "カラス（群れ）",
  "Animals": "動物",
  "Dead tree": "枯れ木",
  "Deer": "シカ",
  "Leather bag": "革袋",
  "Lleldoryn (Druid)": "レルドリン（ドルイド）",
  "Dolmen 1": "ドルメン 1",
  "Dolmen 2": "ドルメン 2",
  "Dolmen 3": "ドルメン 3",
  "Dolmen 4": "ドルメン 4",
  "Gaul Druid House": "ガリアのドルイドの庵",
  "Druid House": "ドルイドの庵",
  "Eagle": "ワシ",
  "Eagles": "ワシ（群れ）",
  "Face pillar": "人面柱",
  "Field 1": "平原 1",
  "Field 2": "平原 2",
  "Field 3": "平原 3",
  "Field 4": "平原 4",
  "Field (dirt)": "平原（土）",
  "Fish": "魚",
  "Fountain": "泉",
  "Archer": "弓兵",
  "Archers": "弓兵",
  "Gaul": "ガリア",
  "Gate": "城門",
  "Axeman": "斧兵",
  "Axemen": "斧兵",
  "Druid": "ドルイド",
  "Ghoul": "グール",
  "Ghouls": "グール",
  "Mraxis (Gaul)": "ムラクシス（ガリア）",
  "Ogox": "オゴクス",
  "Ogox (Gaul)": "オゴクス（ガリア）",
  "Dumnorix": "ドゥムノリクス",
  "Dumnorix (Gaul)": "ドゥムノリクス（ガリア）",
  "Ercenberht": "エルケンベルヒト",
  "Unferth": "ウンフェルス",
  "Beorht": "ベオルヒト",
  "Morrigu": "モリグー",
  "Darhinnox": "ダルヒノクス",
  "Morgatha": "モルガサ",
  "Morgatha (Gaul)": "モルガサ（ガリア）",
  "Horseman": "騎兵",
  "Horsemen": "騎兵",
  "Wooden Outpost": "木造前哨基地",
  "Interactive": "インタラクティブ",
  "Outpost (wooden)": "前哨基地（木造）",
  "Cliff (small) 2": "小崖 2",
  "Cliff (small) 1": "小崖 1",
  "Spearman": "槍兵",
  "Spearmen": "槍兵",
  "Swordsman": "剣士",
  "Swordsmen": "剣士",
  "Viking Lord": "ヴァイキング首領",
  "Viking Lords": "ヴァイキング首領",
  "Peasant (male)": "農民（男）",
  "Woman Warrior": "女戦士",
  "Woman Warriors": "女戦士",
  "Peasant (female)": "農民（女）",
  "Hen": "雌鶏",
  "Cavalry": "騎兵隊",
  "House": "民家",
  "Village (Gaul)": "村（ガリア）",
  "House 1": "民家 1",
  "House 2": "民家 2",
  "House 3": "民家 3",
  "House 4": "民家 4",
  "House 5": "民家 5",
  "House 6": "民家 6",
  "Inn": "宿屋",
  "Keltill": "ケルティル",
  "Keltill (Gaul)": "ケルティル（ガリア）",
  "Roman pillar": "ローマの円柱",
  "Tilted column": "傾いた円柱",
  "Larax": "ララックス",
  "Larax (Gaul)": "ララックス（ガリア）",
  "Lion throne": "獅子の玉座",
  "Brand": "ブランド",
  "Hero 1": "英雄 1",
  "Heardred": "ヘアルドレッド",
  "Hero 2": "英雄 2",
  "Oak stump": "樫の切り株",
  "Objects": "オブジェクト",
  "Outpost": "前哨基地",
  "Peasant": "農民",
  "Peasants": "農民",
  "Roman Arch": "ローマの凱旋門",
  "Roman": "ローマ",
  "Stronghold (Roman)": "要塞（ローマ）",
  "Gladiator": "剣闘士",
  "Gladiators": "剣闘士",
  "Tuvius": "トゥウィウス",
  "Tuvius (Roman)": "トゥウィウス（ローマ）",
  "Julius": "ユリウス",
  "Julius (Roman)": "ユリウス（ローマ）",
  "Cornelius": "コルネリウス",
  "Cornelius (Roman)": "コルネリウス（ローマ）",
  "Pavonius": "パウォニウス",
  "Pavonius (Roman)": "パウォニウス（ローマ）",
  "Caius": "ガイウス",
  "Fabianus": "ファビアヌス",
  "Nigellus": "ニゲルス",
  "Rutilianus": "ルティリアヌス",
  "Victor": "ウィクトル",
  "Marius": "マリウス",
  "Marius (Roman)": "マリウス（ローマ）",
  "Scout": "斥候",
  "Scouts": "斥候",
  "Roman House": "ローマの民家",
  "Village (Roman)": "村（ローマ）",
  "Rib cage": "あばら骨の残骸",
  "Liberatus": "リベラトゥス",
  "Liberati": "リベラトゥス",
  "Rocks 4": "岩 4",
  "Stone Outpost": "石造前哨基地",
  "Outpost (stone)": "前哨基地（石造）",
  "Praetorian": "プラエトリアン",
  "Praetorians": "プラエトリアン",
  "Priest": "神官",
  "Stone SW": "石造（南西）",
  "Stone NW": "石造（北西）",
  "Stone SE": "石造（南東）",
  "Stone NE": "石造（北東）",
  "Principle": "プリンキペス",
  "Hastatus": "ハスタティ",
  "Hastati": "ハスタティ",
  "Tavern": "酒場",
  "Tavern SW": "酒場（南西）",
  "Tavern SE": "酒場（南東）",
  "Temple": "神殿",
  "Tower": "監視塔",
  "Townhall": "町役場",
  "Ruin Door 1": "遺跡の扉 1",
  "Ruin Door 2": "遺跡の扉 2",
  "Village hall": "村役場",
  "Sanctuary": "聖域",
  "Skull tree": "髑髏の木",
  "Sed": "セド",
  "Ship": "大型戦船",
  "Ships": "大型戦船",
  "Boat": "小型船",
  "Boats": "小型船",
  "Wooden SW": "木造（南西）",
  "Wooden SE": "木造（南東）",
  "Wooden NE": "木造（北東）",
  "Wooden NW": "木造（北西）",
  "Ship wreck (large)": "難破船（大）",
  "Ship wreck (small)": "難破船（小）",
  "Roman statue": "ローマの彫像",
  "Stonehenge 1": "ストーンヘンジ 1",
  "Stonehenge 2": "ストーンヘンジ 2",
  "Stone pile": "石積み",
  "Swamp (large)": "大湿地",
  "Swamp 1": "湿地 1",
  "Swamp 2": "湿地 2",
  "Cave": "洞窟",
  "Rocks 5": "岩 5",
  "Rocks 6": "岩 6",
  "Cave SW": "洞窟（南西）",
  "Cave SE": "洞窟（南東）",
  "Teuton tent": "テウトンの天幕",
  "Tent 1": "天幕 1",
  "Tent 2": "天幕 2",
  "Tent 3": "天幕 3",
  "Teuton Archer": "テウトン弓兵",
  "Teuton Archers": "テウトン弓兵",
  "Teuton archer": "テウトン弓兵",
  "Teuton Raider": "テウトン襲撃兵",
  "Teuton Riders": "テウトン騎兵",
  "Teuton Rider": "テウトン騎兵",
  "Tombstone": "墓石"
};
