// UI Data Part 5 (Entries 1200 - 1426)
module.exports = {
  "Object: [ %s1 ]": "オブジェクト：[ %s1 ]",
  "Rome": "ローマ",
  "Place the other side of the cave": "洞窟の反対側の出口を配置",
  "Development score": "発展スコア",
  "Military score": "軍事スコア",
  "Power score": "国力スコア",
  "Overall score": "総合スコア",
  "Minimap": "ミニマップ",
  "Searching for games...": "ゲームを検索中...",
  "Buildings": "建物一覧",
  "Left click to place": "左クリックで配置",
  "Object has no entity": "オブジェクトにエンティティが存在しません",
  "Object is out of map": "オブジェクトがマップ範囲外です",
  "Object must be placed on deep water": "オブジェクトは深水域に配置する必要があります",
  "Buildings cannot be placed on water": "建物は水上に配置できません",
  "Units cannot be placed on deep water": "ユニットは深水域に配置できません",
  "Object is on impassable": "オブジェクトが侵入不可領域にあります",
  "Building is on impassable": "建物が侵入不可領域にあります",
  "Building points are on impassable": "建物の基準点が侵入不可領域にあります",
  "Building is too near to existing settlement": "建物が既存の拠点に近すぎます",
  "Building is too far away from any existing settlement": "建物が既存の拠点から離れすぎています",
  "You have made changes which are not saved. Do you want to save the map?": "未保存の変更があります。マップを保存しますか？",
  "Do you want to save the changes?": "変更内容を保存しますか？",
  "Player %d1": "プレイヤー %d1",
  "%s1 at (%d2, %d3)": "%s1 座標：(%d2, %d3)",
  "Objects in group: %d1": "グループ内オブジェクト数：%d1",
  "Mode: %s1, Size: %d2, %s3: %d4": "モード：%s1、サイズ：%d2、%s3：%d4",
  "Mode: %s1, Size: %d2": "モード：%s1、サイズ：%d2",
  "Auto": "自動",
  "%s1  in %s2 at (%d3, %d4)": "%s1（%s2 内部、座標：(%d3, %d4)）",
  "Terrain [ %s1 ]": "地形 [ %s1 ]",
  "%s1 toggles the fog": "%s1 で戦争の霧を切替",
  "(%d1 gold)\\n%s2": "（%d1 ゴールド）\n%s2",
  "(%d1 gold)\n%s2": "（%d1 ゴールド）\n%s2",
  "(%d1 food)\\n%s2": "（%d1 食料）\n%s2",
  "(%d1 food)\n%s2": "（%d1 食料）\n%s2",
  "Player %s1 lost the game": "プレイヤー %s1 が敗北しました",
  "Your hero %s1 has reached level %d2": "英雄 %s1 がレベル %d2 に到達しました",
  "%s1 paused the game": "%s1 がゲームを一時停止しました",
  "%s1 unpaused the game": "%s1 がゲームを再開しました",
  "%s1 (level %d2)": "%s1（レベル %d2）",
  "One %s1": "1体の %s1",
  "%d1 %s2": "%d1体の %s2",
  "easy": "初級",
  "medium": "中級",
  "hard": "上級",
  "Limit: %s1\\n": "制限：%s1\n",
  "Limit: %s1\n": "制限：%s1\n",
  "Random map: %s1": "ランダムマップ：%s1",
  "Map size: %s1": "マップサイズ：%s1",
  "Victory: %s1": "勝利条件：%s1",
  "World pop: %s1": "世界人口：%s1",
  "Starting gold: %s1": "初期ゴールド：%s1",
  "Game speed: %s1": "ゲーム速度：%s1",
  "Map: %s1": "マップ：%s1",
  "Exploration: %s1": "未探索：%s1",
  "Fog of war: %s1": "戦争の霧：%s1",
  "Shared control: %s1": "操作共有：%s1",
  "Shared support: %s1": "補給共有：%s1",
  "Caves": "洞窟",
  "Teuton tents": "テウトンの天幕",
  "Stonehenges": "ストーンヘンジ",
  "Additional villages": "追加の村",
  "Additional strongholds": "追加の要塞",
  "Enabled": "有効",
  "Disabled": "無効",
  "Empty": "空",
  "Raise/lower": "隆起／沈降",
  "Smooth": "平滑化",
  "Set height": "高さ設定",
  "level": "レベル",
  "amount": "数量",
  "Place circular area": "円形エリア配置",
  "Place rectangular area": "矩形エリア配置",
  "Edit areas": "エリア編集",
  "Tools": "ツール",
  "Height change": "高度変更",
  "Airbrush": "エアブラシ",
  "Noisebrush": "ノイズブラシ",
  "Terrains": "地形一覧",
  "Edit objects": "オブジェクト編集",
  "Place Objects": "オブジェクト配置",
  "Area": "エリア",
  "Height": "高度",
  "Gaul Wood Walls": "ガリアの木壁",
  "Roman Stone Walls": "ローマの石壁",
  "Grass": "草原",
  "Ground": "地面",
  "Can't place": "配置不可",
  "Not enough memory to complete the operation.": "メモリ不足のため処理を完了できません。",
  "Generic read failure.": "一般的な読み込みエラー。",
  "Generic write failure.": "一般的な書き込みエラー。",
  "Operation passed the end of file.": "ファイルの終端を超えた操作です。",
  "Bad open mode.": "不正なファイルオープンモードです。",
  "Cannot truncate file.": "ファイルを切り詰めることができません。",
  "Too many open files.": "開かれているファイルが多すぎます。",
  "Bad volume.": "不正なボリュームです。",
  "Unknown PID.": "不明なPIDです。",
  "File sharing error.": "ファイル共有違反エラー。",
  "Cannot flush file.": "ファイルバッファをフラッシュできません。",
  "No more files.": "これ以上ファイルがありません。",
  "Not ready.": "準備ができていません。",
  "Seek fail. This may be caused by a corrupt savegame file.": "シークに失敗しました。セーブデータが破損している可能性があります。",
  "The specified file cannot be found. Check the spelling.": "指定されたファイルが見つかりません。綴りを確認してください。",
  "Bad file format. This may be caused by a corrupt savegame file.": "ファイル形式が不正です。セーブデータが破損している可能性があります。",
  "Cannot open file. This may be caused by a corrupt savegame file.": "ファイルを開けません。セーブデータが破損している可能性があります。",
  "The specified path cannot be found. Check the spelling.": "指定されたパスが見つかりません。綴りを確認してください。",
  "Access to this file was denied.": "ファイルへのアクセスが拒否されました。",
  "A file with the same name already exists and cannot be overwritten.": "同名のファイルが既に存在し、上書きできません。",
  "The specified disk volume cannot be found.": "指定されたディスクボリュームが見つかりません。",
  "The file is write protected and cannot be overwritten.": "ファイルが書き込み保護されているため上書きできません。",
  "The specified disk is full. Free more space and try again.": "ディスクの空き容量が不足しています。空きを作って再試行してください。",
  "A file with the specified name already exists.": "指定された名前のファイルは既に存在します。",
  "The specified file name and/or path is invalid.": "指定されたファイル名またはパスが無効です。",
  "The map you played this game on when the game was saved (%s1) is missing or has been changed": "セーブ時にプレイしていたマップ（%s1）が存在しないか、変更されています",
  "Error saving scenario/adventure file": "シナリオ／アドベンチャーファイルの保存エラー",
  "Error saving game": "ゲーム保存エラー",
  "Error loading scenario/adventure file": "シナリオ／アドベンチャーファイルの読込エラー",
  "Error loading game": "ゲーム読込エラー",
  "Do you want to replace the existing file '%s1'?": "既存のファイル '%s1' を置き換えますか？",
  "Do you really want to lose your current map and replace it with a randomly generated one": "現在のマップを破棄し、ランダム生成されたマップで上書きしますか？",
  "Random map generation failed - bad map template": "ランダムマップ生成に失敗しました（無効なマップテンプレート）",
  "Select an inn to visit or rightclick to cancel.": "移動先の宿屋を選択するか、右クリックでキャンセルしてください。",
  "You won.": "あなたの勝利です。",
  "Game saved.": "ゲームを保存しました。",
  "Game loaded.": "ゲームを読み込みました。",
  "New conversation": "新規会話",
  "Delete this saved game?": "このセーブデータを削除しますか？",
  "Before testing, the map must be saved. Do you want to save the map?": "テストを開始する前にマップを保存する必要があります。保存しますか？",
  "Game time: %s1:%s2:%s3": "ゲーム時間：%s1:%s2:%s3",
  "From strongholds": "要塞から",
  "From outposts": "前哨基地から",
  "Captured": "占領数",
  "Military": "軍事",
  "Development": "発展",
  "Overall": "総合",
  "Killed": "撃破数",
  "Lost": "喪失数",
  "Maximum": "最大",
  "Gold spent": "消費ゴールド",
  "Food spent": "消費食料",
  "Waiting for player %s1 (%d2)": "プレイヤー %s1 の待機中（%d2）",
  "Player %s1 dropped\\n": "プレイヤー %s1 が切断されました\n",
  "Player %s1 dropped\n": "プレイヤー %s1 が切断されました\n",
  "different game version": "ゲームバージョン不一致",
  "Please insert the Celtic Kings - Rage of War CD!": "『ケルトの王 (Celtic Kings: Rage of War)』のCDを挿入してください！",
  "You don't have the map file '%s1.bfhp' and can't participate in this game.": "マップファイル '%s1.bfhp' を所持していないため、このゲームに参加できません。",
  "Error when launching GameSpy": "GameSpyの起動中にエラーが発生しました",
  "Easy": "初級",
  "Hard": "上級",
  "Overwrite this file?": "このファイルを上書きしますか？",
  "This inn (%s1) is closed.": "この宿屋（%s1）は閉鎖されています。",
  "Click to visit this inn (%s1).": "クリックしてこの宿屋（%s1）へ移動。",
  "Click this inn (%s1) to cancel.": "この宿屋（%s1）をクリックしてキャンセル。",
  "Wind of wisdom": "叡智の風",
  "Starvation": "飢餓",
  "Golden rain": "黄金の雨",
  "Death wish": "死の宿願",
  "Bloodlust": "血の狂乱",
  "Teuton uprising": "テウトン蜂起",
  "%s1 (requires Druid House ritual)": "%s1（要・ドルイドの庵儀式）",
  "%s1 (requires Temple ritual)": "%s1（要・神殿儀式）",
  "Advanced Training": "進階訓練",
  "Archer equipment ready": "弓兵装備の開発完了",
  "Axeman equipment ready": "斧兵装備の開発完了",
  "Cloud of Plague": "疫病の雲",
  "Fastest warrior equipment complete": "最速兵員装備の研究完了",
  "Food Tax": "食料徴税",
  "Ghoul Summoning": "グール召喚",
  "Gladiator equipment ready": "剣闘士装備の開発完了",
  "Gladiator Shows": "剣闘士興行",
  "Herb Amulets of Luck": "幸運の薬草護符",
  "Horseman equipment ready": "騎兵装備の開発完了",
  "Mass Heal": "集団治癒",
  "Military Academy": "軍事士官学校",
  "Praetorian equipment ready": "プラエトリアン装備の開発完了",
  "Principle equipment ready": "プリンキペス装備の開発完了",
  "Scout equipment ready": "斥候装備の開発完了",
  "Spearman equipment ready": "槍兵装備の開発完了",
  "Steel Weapons": "鋼の武器",
  "Woman Warrior equipment ready": "女戦士装備の開発完了",
  "Template Scenario": "テンプレートシナリオ",
  "Unknown Author": "作者不詳",
  "Scenario Game": "シナリオゲーム",
  "Template Adventure": "テンプレートアドベンチャー",
  "Adventure Game": "アドベンチャーゲーム",
  "New Map": "新規マップ",
  "Pause toggled": "一時停止切替",
  "empty phrase": "空の台詞",
  "Replay (finished)": "リプレイ（終了済）",
  "Compiled successfully": "コンパイル成功",
  "Condition script compiled successfully": "条件スクリプトのコンパイルに成功しました",
  "Action script compiled successfully": "アクションスクリプトのコンパイルに成功しました",
  "Return script compiled successfully": "返答スクリプトのコンパイルに成功しました",
  "Human": "人間",
  "Computer": "コンピュータ",
  "Both": "両方",
  "Rescue": "救出",
  "choice": "選択",
  "first": "最初",
  "cycle": "循環",
  "cycle then first": "循環後に最初へ",
  "cycle then random": "循環後にランダム",
  "end": "終了",
  "Size": "サイズ",
  "<None>": "<なし>",
  "Video Mode Unavailable": "画面モード利用不可",
  "Cannot switch to %d1 x %d2 video mode with 65536 colors. Try setting your Windows desktop resolution to this mode and launch the application again.": "65536色 %d1 x %d2 の画面モードに切り替えられません。Windowsデスクトップの解像度を変更してから再起動してください。",
  "Sequences": "シーケンス一覧",
  "Wooden walls": "木壁",
  "Stone walls": "石壁",
  "Debt": "債務",
  "Current map": "現在のマップ",
  "Stronghold": "要塞",
  "Village": "村",
  "Choice text:": "選択肢テキスト：",
  "Condition:": "条件：",
  "Action:": "アクション：",
  "Return:": "返答：",
  "Comments:": "コメント：",
  "Follow-up:": "後続：",
  "Follow-ups:": "後続一覧：",
  "900, 15 mins": "900（15分）",
  "1800, 30 mins": "1800（30分）",
  "2700, 45 mins": "2700（45分）",
  "3600, 1 hour": "3600（1時間）",
  "5400, 1h 30min": "5400（1時間30分）",
  "7200, 2 hours": "7200（2時間）",
  "9000, 2h 30min": "9000（2時間30分）",
  "10800, 3 hours": "10800（3時間）"
};
