// UI Data Part 1 (Entries 0 - 300)
module.exports = {
  "Battle for Stonehenge (normal)": "ストーンヘンジの戦い（通常）",
  "A mountainous area which is dominated by a powerful Roman AI. The map holds five players whose goal is to eliminate the AI.\\nIt is strongly recommended that all players play in one team.":
    "強力なローマAIが支配する山岳地帯。最大5名のプレイヤーが参加でき、AIの殲滅を目指す。\nすべてのプレイヤーが1つのチームを結成して挑むことを強く推奨。",
  "Four kingdoms (normal)": "四つの王国（通常）",
  "A map with mountainous terrain and narrow passages, with a central Roman stronghold that can give an advantage to the player who manages to keep it.\\n":
    "山岳地形と狭い通路が特徴のマップ。中央にあるローマの要塞を確保・維持できたプレイヤーが大きな優位を得る。\n",
  "I of the sea (normal)": "海の瞳（通常）",
  "A large island map that is filled with neutral forces that guard various areas. The battles could take place either on the central island or those surrounding it. \\nThe map is best suited for two teams of two players each.":
    "各所に中立勢力が駐留する広大な島嶼マップ。戦いは中央の島、あるいはそれを取り巻く島々で繰り広げられる。\n2人×2チームの対戦に最適。",
  "Island chaos (normal)": "群島の乱（通常）",
  "An island map that has three large islands, with two strongholds each. While players could attack each other on sea and land there are things to be gained by exploring the smaller islands.\\nThe map is best suited for three teams of two players each.":
    "それぞれ2つの要塞を持つ3つの大島からなるマップ。海陸両面での攻防に加え、小島を探索することで様々な恩恵が得られる。\n2人×3チームの対戦に最適。",
  "Island troubles (huge)": "波乱の群島（巨大）",
  "A sea map in which battles could take place in sea as well as on land. Four of the players start on their own separate islands, while the rest have direct contact with one another.":
    "海戦と陸戦が入り混じる海洋マップ。4名のプレイヤーは独立した孤島から開始し、残りのプレイヤーは陸続きで対峙する。",
  "Island war (normal)": "島嶼の戦争（通常）",
  "An islands map in which the western islands are occupied by Gauls and the eastern by Romans. There exist also a number of neutral islands populated by Teutons, which will give an advantage to the person who captures them.\\nThe map is best suited for two teams of three players each.":
    "西の島々をガリアが、東の島々をローマが占拠するマップ。テウトン人が住む中立の島々も点在し、それらを制圧した者が優位に立つ。\n3人×2チームの対戦に最適。",
  "Mountain battlegrounds (normal)": "山岳の古戦場（通常）",
  "A land map that gives the players the opportunity to match the strength of their armies in the mountainous circle in the middle of the area.":
    "マップ中央の円形山岳地帯で軍勢の総力を競い合う陸上戦マップ。",
  "North and South (normal)": "南と北（通常）",
  "A land map with a mountain chain that splits the area in two, which makes the passage from one part to the other difficult. \\nThe map is best suited for two teams of three players each.":
    "巨大な連峰が地域を南北に二分し、東西の行き来を阻む陸上マップ。\n3人×2チームの対戦に最適。",
  "River of Teutons (normal)": "テウトンの大河（通常）",
  "A map with two teams of three players each in which the participants are additionally burdened by the constant attack of passing Teutons, as well as a large number of Teuton tents in the area.":
    "3人×2チーム用のマップ。プレイヤー同士の激突に加え、絶え間なく襲来するテウトン人や無数に点在する天幕への対処が求められる。",
  "Riverside (small)": "河畔の戦い（小）",
  "A land map with a river dividing the area in two parts - one under Roman control, the other belonging to the Gauls.\\nThe map is best suited for head to head games.\\n":
    "中央を流れる川が地域をローマ領とガリア領に二分する陸上マップ。\n1対1の真剣勝負に最適。\n",
  "Shattered lands (normal)": "引き裂かれし大地（通常）",
  "A coastal map with two major peninsulas, one governed by the Romans, the other by the Gauls. Because of the broken terrain battles are possible in sea as well as on land.\\nThe map is best suited for two teams of four players each.\\n":
    "ローマとガリアがそれぞれ治める2大半島を擁する海岸マップ。入り組んだ地形により海戦と陸戦の双方が展開する。\n4人×2チームの対戦に最適。\n",
  "The battle for survival (normal)": "生存への戦い（通常）",
  "A land mission in which the player must escape the lake he is prisoner of and capture a stronghold in less than 3 minutes, before doing anything else.\\nThis map can be played only by human players.\\n":
    "幽閉された湖水地帯から脱出し、3分以内に要塞を占領しなければならない陸上ミッション。\n※人間のプレイヤー専用マップ。\n",
  "The cross shaped islands (normal)": "十文字諸島（通常）",
  "A sea map filled with islands of various sizes, where the players don't always have direct access with one another.":
    "大小様々な島々が十文字状に連なる海洋マップ。プレイヤー間の直接的な往来には海上路の確保が必要。",
  "The deadly triangle (normal)": "死の三角地帯（通常）",
  "A three person map in which every player is for himself, and while attacking one's enemies directly could lead to victory there are a number of islands that could give an advantage to those who dare seek it.":
    "3名による三つ巴の乱戦マップ。敵への直接攻撃だけでなく、周囲の島々をいち早く掌握した者が勝利を手にする。",
  "The mountain wall (normal)": "険しき山壁（通常）",
  "A land map with two teams of three players each, in which both sides are separated by a large mountain chain that separates the area in two.":
    "中央を横断する巨大な山脈によって両陣営が隔てられた、3人×2チーム用の陸上マップ。",
  "The northern coast (normal)": "北の海岸（通常）",
  "A coastal map with rough terrain that focuses mainly on land battles.\\nThe map is best suited for free-for-all games.":
    "険しい地形が広がる海岸マップ。陸上での乱戦が主眼となる。\n個人戦（バトルロイヤル）に最適。",
  "The Teuton Sun (huge)": "テウトンの太陽（巨大）",
  "A land map abundant with numerous lakes that make traveling difficult. The one who manages to gain control of the Roman stronghold guarded by a vast number of Teutons in the center of the area will gain a great advantage.":
    "無数の湖が点在し進軍を阻む広大な陸上マップ。中央で多数のテウトン人に守られたローマ要塞を奪取した者が圧倒的な覇権を握る。",
  "Trial of heroes (normal)": "英雄の試練（通常）",
  "A land map with rough terrain in which each player is given a hero to start with. Since no heroes can be built each player must protect his hero as best he could.":
    "険しい地形の陸上マップ。各プレイヤーは最初から1名の英雄を与えられる。新たな英雄の雇用は不可能なため、初期英雄を決して失ってはならない。",
  "Volcano (small)": "火山（小）",
  "A mountainous map in which the four strongholds are located near a huge volcano. Because of this there is absolutely no vegetation in the area, nor are there any neutral enemies.\\n":
    "巨大な火山の周囲に4つの要塞が配置された山岳マップ。火山灰のため草木は生えず、中立勢力も一切存在しない。\n",
  "X marks the spot (normal)": "秘宝の眠る地（通常）",
  "An island map that combines land battles and sea travel. While the players could concentrate their battles on the central island, there exist four smaller islands that could be explored.\\n":
    "陸戦と航海が融合した島嶼マップ。主戦場となる中央の島に加え、探索可能な4つの小島が配置されている。\n",

  // Items
  "Bear teeth amulet": "熊の牙の護符",
  "Adds 4 to max attack.": "最大攻撃力 +4。",
  "Herb amulet of luck": "幸運の薬草護符",
  "Adds 4 to piercing defence.": "刺突防御 +4。",
  "Belt of might": "剛力のベルト",
  "Adds 4 to slashing defence.": "斬撃防御 +4。",
  "Rye spikes": "ライ麦の穂",
  "Distributes up to 200 food among nearby friendly units.": "周囲の味方ユニットに最大200の食料を分配補給する。",
  "Snake skin": "ヘビの皮",
  "Adds 10 to attack.": "攻撃力 +10。",
  "Belt of snakes": "蛇の帯",
  "Adds 30 to attack.": "攻撃力 +30。",
  "Eagle feather": "ワシの羽",
  "Adds 200 max health.": "最大体力 +200。",
  "Feather amulet": "羽毛の護符",
  "Adds 400 max health.": "最大体力 +400。",
  "King's Belt": "王者の帯",
  "Adds 600 max health and 10 slashing and piercing defense.": "最大体力 +600、斬撃防御 +10、刺突防御 +10。",
  "Poison Mushroom": "毒キノコ",
  "When used adds 1 level permanently. The bearer must have at least 90% health.": "使用時、レベルが恒久的に1上昇する（所持者の体力が90%以上必要）。",
  "Healing herbs": "薬草",
  "Restores the health of the bearer.": "所持者の体力を回復する。",
  "Healing water": "癒しの水",
  "Distributes up to 1000 health among nearby friendly units.": "周囲の味方ユニットに最大1000の体力を分配回復する。",
  "Boar tooth": "イノシシの牙",
  "Adds 25 experience. When used damages the target unit taking health from the bearer.": "経験値 +25。使用時、所持者の体力を消費して対象ユニットにダメージを与える。",
  "Boar teeth": "イノシシの大牙",
  "Adds 5 levels.": "レベルを直接5上昇させる。",
  "Horn of victory": "勝利の角笛",
  "Damages 12 nearby enemy units with 60 points.": "周囲の敵ユニット最大12体に各60ダメージを与える。",
  "Ash of druid heart": "ドルイドの心臓の灰",
  "Restores the health of the bearer and 8 nearby friendly units.": "所持者および周囲の味方ユニット最大8体の体力を回復する。",
  "Finger of death": "死の指",
  "Kills 3 nearby enemy units. Does not affect heroes.": "周囲の敵ユニット最大3体を即死させる（英雄には無効）。",
  "Fur gloves of health": "体力の毛皮手袋",
  "Adds 1200 health. When used heals one friendly unit taking health from the bearer.": "体力 +1200。使用時、所持者の体力を消費して味方ユニット1体を治療する。",
  "Concentration stone": "集中の石",
  "Adds 60 max attack. When used heals the bearer taking the health of a friendly unit.": "最大攻撃力 +60。使用時、味方ユニット1体の体力を吸収して所持者の体力を回復する。",
  "Bloodstone": "血石",
  "Faded gem": "色褪せた宝玉",
  "The gem is still too weak to channel the Power of the Goddess.": "この宝玉はまだ魔力が弱く、女神の力を導くことができない。",
  "Glowing gem": "輝く宝玉",
  "The gem now can channel the Power of the Goddess.": "この宝玉は女神の力を導く輝きを放っている。",
  "Gem of Power": "力の宝玉",
  "The gem makes the Power of the Goddess flow through your veins.": "この宝玉は女神の力を所持者の全身に宿らせる。",

  // Rituals
  "Wind of wisdom ritual": "叡智の風の儀式",
  "Increases the level of all existing units": "全ユニットのレベルを上昇させる",
  "Starvation ritual": "飢餓の儀式",
  "Slowly decreases all food supplies for 2 minutes": "2分間にわたり全食料備蓄を徐々に減少させる",
  "Golden rain ritual": "黄金の雨の儀式",
  "Slowly adds gold to every settlement storage for 2 minutes": "2分間にわたり全拠点のゴールドを持続的に増加させる",
  "Death wish ritual": "死の宿願の儀式",
  "Drains the life out of every druid and priest for 1 minute": "1分間にわたり全ドルイドと神官の生命力を激しく奪う",
  "Bloodlust ritual": "血の狂乱の儀式",
  "Enables all units to inflict maximum damage for 6 minutes": "6分間にわたり全ユニットの攻撃が常に最大ダメージとなる",
  "Teuton uprising ritual": "テウトン蜂起の儀式",
  "Starts a Teuton uprising in every Teuton tent": "すべてのテウトンの天幕でテウトン人の一斉蜂起を引き起こす",

  // Commands & Interface (97 - 300)
  "Transport Party": "隊を移動",
  "Transports the party to another map": "隊を別のマップへ移動させる",
  "Stand ground": "その場を死守",
  "Move": "移動",
  "Attack": "攻撃",
  "Capture": "占領",
  "Explore": "探索",
  "Attach to hero": "英雄の指揮下に配属",
  "Train units": "部隊訓練",
  "Train combat with fellow warriors": "味方戦士と戦技を鍛錬する",
  "Patrol": "巡回",
  "Build catapult": "カタパルト建造",
  "Builds immobile long range catapult": "長射程の据え置き型カタパルトを建造する",
  "Keeps army in battle formation (applies bonus)": "軍隊を陣形に維持する（陣形ボーナス適用）",
  "Selects Line formation": "横陣を選択",
  "Select Block formation": "方陣を選択",
  "Select Horse wings formation": "騎兵翼陣を選択",
  "Leave army": "配属解除",
  "Leaves the attached units on their own": "配属部隊を解任し単独行動に戻す",
  "Help Sacrifice": "生贄の儀式を支援",
  "Learn from unit": "部隊から学習",
  "Gains knowledge from a more experienced unit": "より熟練した部隊から経験を吸収する",
  "Heal unit": "治療",
  "Create Cloud of Plague": "疫病の雲を発生",
  "Creates a cloud that slowly kills all affected units": "範囲内のユニットを徐々に蝕み倒す毒雲を発生させる",
  "Cloud of Plague, %s1 (requires Temple ritual)": "疫病の雲、%s1（要・神殿儀式）",
  "Summon ghoul": "グール召喚",
  "Summons a controllable ghoul that drains the life of nearby enemy units": "敵の生命力を吸い取る操作可能なグールを召喚する",
  "Ghoul Summoning, %s1 (requires Druid House ritual)": "グール召喚、%s1（要・ドルイドの庵儀式）",
  "Beast control": "野獣支配",
  "Takes control of one or more nearby animals (eagle, deer, wolf or crow)": "付近の野生動物（ワシ、シカ、オオカミ、カラス）を支配下に置く",
  "Beast control, %s1 (requires Druid House ritual)": "野獣支配、%s1（要・ドルイドの庵儀式）",
  "Mass heal": "集団治癒",
  "Heals nearby friendly units (sacrificing the person's life)": "術者の命を捧げ、周囲の味方ユニットを治療する",
  "Mass Heal, %s1 (requires Druid House ritual)": "集団治癒、%s1（要・ドルイドの庵儀式）",
  "Invisibility": "不可視の術",
  "Renders all units in area invisible": "効果範囲内の全ユニットを透明化する",
  "Invisibility, %s1 (requires Druid House ritual)": "不可視の術、%s1（要・ドルイドの庵儀式）",
  "Wrath of Jupiter": "ユピテルの怒り",
  "Channels the Wrath of Jupiter hurting the target (sacrificing the person's life)": "術者の命を捧げ、対象に主神ユピテルの激しい雷撃を放つ",
  "Wrath of Jupiter, %s1 (requires Temple ritual)": "ユピテルの怒り、%s1（要・神殿儀式）",
  "Unload caravan": "物資荷降ろし",
  "Load 1000 gold": "ゴールド1000を積載",
  "Load 250 gold": "ゴールド250を積載",
  "Load 1000 food": "食料1000を積載",
  "Load 250 food": "食料250を積載",
  "Fire at will": "自由射撃",
  "Stop firing": "射撃中止",
  "Dismantle": "解体",
  "Repair": "修理",
  "Tribute": "貢納",
  "Sends resources to another location": "他の拠点へ資源を輸送する",
  "Click on a townhall, village or outpost to start sending resources": "町役場、村、または前哨基地をクリックして資源輸送を開始",
  "Stop sending resources": "資源輸送を停止",
  "Buy 500 food": "食料500を購入",
  "Call peasants": "農民を募集",
  "Calls 5 peasants of the population": "要塞人口から農民5人を召集する",
  "Create mule with 250 food": "食料250積載の荷ロバを生産",
  "Create mule with 1000 food": "食料1000積載の荷ロバを生産",
  "Create mule loaded with 250 gold": "ゴールド250積載の荷ロバを生産",
  "Create mule loaded with 1000 gold": "ゴールド1000積載の荷ロバを生産",
  "Sell food": "食料売却",
  "Slowly exchanges stored food for gold": "備蓄食料を徐々に売却してゴールドに換金する",
  "yes": "はい",
  "Stop selling food": "食料売却を停止",
  "no": "いいえ",
  "Call Druid": "ドルイドを招聘",
  "Ritual chamber": "儀式の小部屋",
  "Allows Druids to practice their skills": "ドルイドの修行・儀式を解放",
  "Allows Ghoul summoning ritual": "グール召喚の儀式を解放",
  "Allows Mass heal ritual": "集団治癒の儀式を解放",
  "Allows Beast control ritual": "野獣支配の儀式を解放",
  "Allows Invisibility ritual": "不可視の儀式を解放",
  "Call Priest": "神官を招聘",
  "Altar of Jupiter": "ユピテルの祭壇",
  "Allows Priests to practice their skills": "神官の修行・奇跡を解放",
  "Allows Cloud of Plague ritual": "疫病の雲の儀式を解放",
  "Allows Wrath of Jupiter ritual": "ユピテルの怒りの儀式を解放",
  "Arrows": "矢の開発",
  "Allows Archers": "弓兵の訓練を解放",
  "Tridents": "三叉槍の開発",
  "Allows Gladiators": "剣闘士の訓練を解放",
  "Pikes": "長槍の開発",
  "Allows Principles": "プリンキペスの訓練を解放",
  "Horseshoes": "蹄鉄の開発",
  "Allows Scouts": "斥候の訓練を解放",
  "Spike armor": "棘付き鎧の開発",
  "Allows Praetorians": "プラエトリアンの訓練を解放",
  "Steel weapons": "鋼の武器",
  "Equips level 4 Swordsmen and Archers": "レベル4の剣士と弓兵を配備",
  "Axes": "斧の開発",
  "Allows Axemen": "斧兵の訓練を解放",
  "Spears": "槍の開発",
  "Allows Spearmen": "槍兵の訓練を解放",
  "Allows Horsemen": "騎兵の訓練を解放",
  "Woman armor": "女性用防具",
  "Allows Woman Warriors": "女戦士の訓練を解放",
  "Fast warrior equipment": "兵員装備の迅速化 I",
  "Equips units twice as fast": "ユニット装備速度が2倍に向上",
  "Faster warrior equipment": "兵員装備の迅速化 II",
  "Equips units four times as fast": "ユニット装備速度が4倍に向上",
  "Fastest warrior equipment": "兵員装備の迅速化 III",
  "Equips units eight times as fast": "ユニット装備速度が8倍に向上",
  "Equip Swordsman": "剣士を装備",
  "Equip Archer": "弓兵を装備",
  "Equip Axeman": "斧兵を装備",
  "Equip Spearman": "槍兵を装備",
  "Equip Horseman": "騎兵を装備",
  "Equip Woman Warrior": "女戦士を装備",
  "Equip Hastatus": "ハスタティを装備",
  "Equip Gladiator": "剣闘士を装備",
  "Equip Principle": "プリンキペスを装備",
  "Equip Scout": "斥候を装備",
  "Equip Praetorian": "プラエトリアンを装備",
  "Increase population": "人口増加",
  "Adds 10 peasants to the stronghold population": "要塞人口に農民10人を追加",
  "Free beer": "無料ビール",
  "Allows advanced Tavern commands and upgrades": "酒場の高度なコマンドとアップグレードを解放",
  "Free wine": "無料ワイン",
  "Import horses": "名馬の輸入",
  "Equip level 10 Scouts": "レベル10の斥候を配備",
  "Buy map": "地図の購入",
  "Explores large area around the stronghold": "要塞周囲の大規模なエリアを探索",
  "Scout area": "区域偵察",
  "Temporarily removes fog of war in chosen area": "指定地域の戦争の霧を一時的に晴らす",
  "Free Wine": "無料ワイン",
  "Investment": "商業投資",
  "Returns 6000 gold after the investment is complete": "投資完了後に6000ゴールドを回収",
  "Food tax": "食料徴税",
  "Collects food tax from population": "住民から食料税を徴収",
  "Nordic trade routes": "北方交易路",
  "Starts equipping all units with Bear Teeth Amulet (+4 max attack)": "全ユニットに「熊の牙の護符（最大攻撃力+4）」を支給",
  "Herb amulets of Luck": "幸運の薬草護符",
  "Starts equipping all units with Herb Amulet of Luck (+4 piercing defence)": "全ユニットに「幸運の薬草護符（刺突防御+4）」を支給",
  "Belts of Might": "剛力のベルト",
  "Starts equipping all units with Belt of Might (+4 slashing defence)": "全ユニットに「剛力のベルト（斬撃防御+4）」を支給",
  "Get loan": "借款を受ける",
  "Borrows 4000 gold at 10% interest": "利息10%で4000ゴールドを借入",
  "Free Beer": "無料ビール",
  "Repay loan": "借款返済",
  "Gives all current gold to repay the loan (without interest)": "手持ちの全ゴールドを充てて借款を返済（利息免除）",
  "Fights": "角闘大会",
  "Allows advanced Arena commands and upgrades": "闘技場の高度なコマンドとアップグレードを解放",
  "Gladiator shows": "剣闘士興行",
  "Training": "訓練 I",
  "Allows training of units to level 4": "ユニットをレベル4まで訓練可能",
  "Advanced training": "訓練 II",
  "Allows training of units to level 8": "ユニットをレベル8まで訓練可能",
  "Special training": "訓練 III",
  "Allows training of units to level 12": "ユニットをレベル12まで訓練可能",
  "Hire hero": "英雄を雇用",
  "Hire Viking Lord": "ヴァイキング首領を雇用",
  "Shrine of Thor": "トールの神棚",
  "Attracts better Viking Lords": "より屈強なヴァイキング首領を呼び寄せる",
  "Hire Liberati": "解放闘士を雇用",
  "Hires a group of 10 Liberati": "リベラトゥス10体編成部隊を雇用",
  "Liberati guild": "解放闘士ギルド",
  "Preserves the experience of the best Liberati": "歴戦のリベラトゥスの経験値を保持",
  "Military academy": "軍事士官学校",
  "Advances new heroes to level 12": "新規雇用英雄の初期レベルを12に引き上げ",
  "Battle tactics": "戦術研究",
  "Doubles the experience from battles": "戦闘で得られる経験値を2倍にする",
  "Open Gate": "城門を開く",
  "Close Gate": "城門を閉じる",
  "Create Battle ship": "大型戦船を建造",
  "Create boat with 250 food": "食料250積載の小型船を建造",
  "Create boat with 1000 food": "食料1000積載の小型船を建造",
  "Create boat with 250 gold": "ゴールド250積載の小型船を建造",
  "Create boat with 1000 gold": "ゴールド1000積載の小型船を建造",
  "Land units here": "ここに部隊を上陸させる",
  "Hover over that point": "その地点にカーソルを合わせる",
  "Click to move at the point": "クリックしてその地点へ移動",
  "Right-click to move at the point": "右クリックしてその地点へ移動",
  "Right-click to transport from this Inn": "右クリックしてこの宿屋から移動",
  "Click to attack this hero": "クリックしてこの英雄を攻撃",
  "Right-click to attack this hero": "右クリックしてこの英雄を攻撃",
  "Click to attack this unit": "クリックしてこのユニットを攻撃",
  "Right-click to attack this unit": "右クリックしてこのユニットを攻撃",
  "Click to attack this building": "クリックしてこの建物を攻撃",
  "Right-click to attack this building": "右クリックしてこの建物を攻撃",
  "Click to advance to this position": "クリックしてこの位置へ前進",
  "Right-click to advance to this position": "右クリックしてこの位置へ前進",
  "Right-click to attack this type of units": "右クリックしてこの種類のユニットを攻撃",
  "Approach": "接近",
  "Right-click to approach": "右クリックして接近",
  "Walls cannot be captured, only attacked": "防壁は占領できません（攻撃のみ可能）",
  "Gates cannot be captured, only attacked": "城門は占領できません（攻撃のみ可能）",
  "Towers cannot be captured, only attacked": "監視塔は占領できません（攻撃のみ可能）",
  "Click to capture this settlement": "クリックしてこの拠点を占領",
  "Right-click to capture this settlement": "右クリックしてこの拠点を占領",
  "Click to explore from this point": "クリックしてここから探索開始",
  "Click to attach to hero": "クリックして英雄に配属",
  "Right-click to attach to hero": "右クリックして英雄に配属",
  "Click to enter this cave": "クリックしてこの洞窟に入る",
  "Right-click to enter this cave": "右クリックしてこの洞窟に入る",
  "Click to enter this building": "クリックしてこの建物に入る",
  "Right-click to enter this building": "右クリックしてこの建物に入る",
  "Right-click to get all items": "右クリックしてすべてのアイテムを回収",
  "Click to patrol this position": "クリックしてこの位置を巡回",
  "Select a place to build catapult": "カタパルトの建造地点を選択",
  "Right-click to board this ship": "右クリックしてこの船に乗船",
  "Right-click to move the hero to this position": "右クリックして英雄をこの位置へ移動",
  "Right-click to join ritual": "右クリックして儀式に参加"
};
